extends: ["spectral:oas"]

rules:
  path-params: off
  operation-operationId: off
  e-mail-in-description:
    description: Should use email instead of e-mail in descriptions
    severity: warn
    given: "$..*[?(@property === 'description')]"	
    then:
      function: pattern
      functionOptions:
        notMatch: "\\be-mail\\b"

  should-include-operation-summary:
    description: Operation summary should be included
    severity: warn
    given: "$.paths.*[?( @property === 'get' || @property === 'put' || @property === 'post' || @property === 'delete' || @property === 'options' || @property === 'head' || @property === 'patch' || @property === 'trace' )]"
    then:
      - field: "summary"
        function: truthy        

  should-include-response-examples:
    description: At least one example should be included for each API response
    severity: warn
    given: "$.paths..responses.*.content.*"
    then:
      - field: "example"
        function: truthy

  should-include-response-schema:
    description: At least one example should be included for each API response
    severity: warn
    given: "$.paths..responses.*.content.*"
    then:
      - field: "schema"
        function: truthy
